# fly.toml file generated for taskit on 2022-11-16T09:08:17Z

app = "taskit"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT=8080
  CLIENT_ORIGIN_URL = "http://localhost:4040"
  AUTH0_AUDIENCE = "https://hello-world.example.com"
  AUTH0_DOMAIN = "dev-onbdt8c3z3jnm7rk.us.auth0.com"
  DB_USER = "taskit"
  DB_PASSWORD = "mhGDmCK8eMgqYzke"
  DB_URL = "mongodb+srv://taskit:mhGDmCK8eMgqYzke@cluster0.4zrmrcr.mongodb.net/taskit?retryWrites=true&w=majority"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 8080

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
    protocol = "http"
